server:
  port: 8761

eureka:
  instance:
    hostname: peer1
     #是否显示IP地址
    ip-address: true
    prefer-ip-address: true
    #表明是eureka server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://gaobin:123@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://peer2:8762/eureka/
  server:
      # 关闭自我保护机制
      enable-self-preservation: false
      # 每隔10s扫描服务列表，移除失效服务 默认是60s
      eviction-interval-timer-in-ms: 10000

spring:
  application:
    name: peer1
#  security:
#    basic:
#      enabled: true
#    user:
#      password: 123
#      name: gaobin